### ISSUE TITLE
There is a bug on returning context of zero length buffer

### ISSUE THREAD

**Issue by ochaton** [gisle/digest-md5#14]
Hey! We've got problems on our production servers because of very non-pretty bug. When we call context on buffer with length of 64 bytes, or 128 bytes (etc...)  it returns as 3-rd parameter non-zero string. There is very necessary patch here:

https://github.com/afresh1/digest-md5/commit/152c76790cc519b71be2516f9f410515523edb1c

Please, could you merge it?!

**Comment by toddr** [comment]
I believe you're referring to https://github.com/Dual-Life/digest-md5/pull/12 which is being reviewed now. If this is not the case, please let me know. or open a case here https://github.com/Dual-Life/digest-md5/issues

**Comment by ochaton** [comment]
Yeah, just tested https://metacpan.org/pod/Digest::MD5
Now it's totally fine.
