### ISSUE TITLE
Bug #107528: Unable to restore context on "even" numbers

### ISSUE THREAD

**Issue by afresh1** [gisle/digest-md5#9]
I didn't see any feedback for several bugs on rt.cpan.org, is that still the correct place to post bugs for this or if they belong here on Github now.  I can add more details if that's the case and I did test it on Linux with plenv and a stock perl 5.22.0.

https://rt.cpan.org/Public/Bug/Display.html?id=107528

Perhaps @flimzy wants to look?

I do have a patch that the tests pass with, but it's part of ripping out the guts of MD5.xs to use the OpenBSD version.
https://github.com/afresh1/OpenBSD-perl/blob/master/patches/GOOD/use_our_MD5.patch

The relevant bit is that I set `ST(2)` to be an empty string and only copy the buffer if there is one.  I'm not exceedingly familiar with perlguts so there could be a better way.

```
+   ST(2) = sv_2mortal(newSVpv("",0));
+   if (((ctx->count >> 3) & (MD5_BLOCK_LENGTH - 1)) != 0)
+       ST(2) = sv_2mortal(newSVpv((char *)ctx->buffer,
```

**Comment by toddr** [comment]
RT 107528 was moved to https://github.com/Dual-Life/digest-md5/issues/2

**Comment by afresh1** [comment]
It got merged in the dual-life repository.
